### ISSUE TITLE
Cannot read property 'emulate' of undefined

### ISSUE THREAD

**Issue by sibelius** [aholachek/bundle-wizard#12]
TypeError: Cannot read property 'emulate' of undefined
    at downloadCoverage (/Users/sibelius/.npm/_npx/4891/lib/node_modules/bundle-wizard/src/functions/downloadCoverage.js:93:16)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async main (/Users/sibelius/.npm/_npx/4891/lib/node_modules/bundle-wizard/src/index.js:29:28)

**Comment by aholachek** [comment]
This is weird. I just made a release -- 1.4.0 -- that upgrades puppeteer to v5, would you mind trying it out and telling me if you still see the same problem?

**Comment by sibelius** [comment]
I think it was a mismatch of versions, tks
