### ISSUE TITLE
Chrome could not be killed

### ISSUE THREAD

**Issue by seonglae** [aholachek/bundle-wizard#32]
```
📋  Writing coverage file to disk...
Error: Chrome could not be killed Command failed: taskkill /pid 19896 /T /F
ERROR: The process "19896" not found.

    at C:\Users\Seonglae\AppData\Local\npm-cache\_npx\bb7f27a7b68f073a\node_modules\chrome-launcher\dist\chrome-launcher.js:282:28
    at new Promise (<anonymous>)
    at Launcher.kill (C:\Users\Seonglae\AppData\Local\npm-cache\_npx\bb7f27a7b68f073a\node_modules\chrome-launcher\dist\chrome-launcher.js:262:16)
    at Object.<anonymous> (C:\Users\Seonglae\AppData\Local\npm-cache\_npx\bb7f27a7b68f073a\node_modules\chrome-launcher\dist\chrome-launcher.js:54:29)
    at Generator.next (<anonymous>)
    at C:\Users\Seonglae\AppData\Local\npm-cache\_npx\bb7f27a7b68f073a\node_modules\chrome-launcher\dist\chrome-launcher.js:13:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Seonglae\AppData\Local\npm-cache\_npx\bb7f27a7b68f073a\node_modules\chrome-launcher\dist\chrome-launcher.js:9:12)
    at Object.kill (C:\Users\Seonglae\AppData\Local\npm-cache\_npx\bb7f27a7b68f073a\node_modules\chrome-launcher\dist\chrome-launcher.js:49:28)
    at downloadCoverage (C:\Users\Seonglae\AppData\Local\npm-cache\_npx\bb7f27a7b68f073a\node_modules\bundle-wizard\src\functions\downloadCoverage.js:163:30)     

⬇️   Downloading sourcemaps...
⚠️  No sourcemaps could be downloaded, analysis cannot proceed.
```
`npx bundle-wizard google.com` - this happens

**Comment by thexpand** [comment]
I can confirm that this is happening to me as well. Any solutions?

**Comment by ChristopherPHolder** [comment]
I am having the same error, any solution? 
This issue went away for me when i reverted to version 1.6.0
